# Generated by Django 6.0.2 on 2026-02-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Customer'), ('churned', 'Churned')], default='lead', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('meta_ads', 'Meta Ads'), ('organic', 'Organic'), ('referral', 'Referral'), ('other', 'Other')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='contacts_co_email_25f973_idx'), models.Index(fields=['status'], name='contacts_co_status_d675ed_idx'), models.Index(fields=['assigned_to'], name='contacts_co_assigne_0f9574_idx')],
            },
        ),
    ]
